keys:
	- d10
	- d12
	- d20
	- d4
	- d6
	- d8
	- 比大小
	- 骰子
	- 🎲
secondary_keys: []
comment: 玩法：骰娘base
content: |-
	当他人谈论起形似“1d6”的语句时，这很可能是指代掷骰子。
	XdY，即扔出X个Y面骰子
	以下是一些随机数，在你需要时[从前往后]取数：
token_size: 60
constant: false
insertion_order: 710
extensions:
	position: 1
	selectiveLogic: 0
	match_whole_words: false
	case_sensitive: null
	prevent_recursion: true
	exclude_recursion: true
	delay_until_recursion: false
	scan_depth: 4
	sticky: 0
	cooldown: 0
	delay: 0
